# see https://github.com/sdras/awesome-actions for a good list of available action
name: Github-CI

on: [push, pull_request]

jobs:

  lint:

    name: "ts-lint"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install depedencies
      run: |
        npm ci
    - name: Lint Code
      run: npm run lint

  build:

    name: "${{ matrix.os }}/Node-${{matrix.node-version}}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]
        # code-version: [stable, insiders]

    steps:
    - uses: actions/checkout@v2
    - name: start docker containers
      run: |
        cd tests
        docker-compose up -d
        cd ..
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - run: npm test
      env:
        CI: true

  publish:
    # only if all tests complete and the commit is tagged as a release
    name: Publish to Marketplace
    needs: [lint, build]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: lannonbr/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_PUB }}